version: '3.8'

services:
  app:
    build: .
    container_name: erms-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@db:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=SYSTEM
      - SPRING_DATASOURCE_PASSWORD=p@ss123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - db
    networks:
      - erms-network

  db:
    image: gvenzl/oracle-xe:21-slim
    container_name: erms-db
    environment:
      - ORACLE_PASSWORD=p@ss123
      - ORACLE_DATABASE=XEPDB1
    ports:
      - "1522:1522"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - erms-network

volumes:
  oracle_data:

networks:
  erms-network:
    driver: bridge